[package]
name = "ned"
version = "1.2.1"
authors = ["Nev Delap <nevdelap@gmail.com>"]

[dependencies]
ansi_term = "0.11.*"
getopts = "0.2.*"
glob = "0.2.*"
libc = "0.2.*"
regex = "1.0.*"
time = "0.1.*"
walkdir = "2.1.*"

[profile.release]
lto = true
